---


# SSH - geerlingguy.security
security_ssh_password_authentication: "yes"
security_ssh_permit_root_login: "yes"

security_autoupdate_enabled: false
security_autoupdate_reboot: false
security_autoupdate_reboot_time: "03:00"
security_autoupdate_mail_to: ""
security_autoupdate_mail_on_error: false
