---
- name: Reload daemon
  ansible.builtin.systemd:
    daemon_reload: true

- name: Restart samba services
  ansible.builtin.service:
    name: "{{ item }}"
    state: restarted
  with_items: "{{ samba_services }}"
