---

- name: Setup pve
  hosts: pve
  vars:
    pve: true
    use_official_security: false
  roles:
    - role: sys-mirror-acceleration
    - role: pve-remove-nag
    - role: pve-vgpu
      tags: ["vgpu"]
    - role: sys-disks
