---

- name: Setup pve.
  hosts: pve
  vars:
    pve: true
    use_official_security: false
  roles:
    - role: sys-mirror-acceleration
    - role: pve-remove-nag
    - role: geerlingguy.security
      tags: ["security"]
    - role: pve-vgpu
      tags: ["vgpu"]

- name: Setup penguin-logistics.
  hosts: penguin-logistics
  roles:
    - role: fs-mergerfs
      tags: ["mergerfs"]
    - role: fs-mount
    - role: share-samba
      tags: ["samba"]
