---

# credit: https://johnscs.com/remove-proxmox51-subscription-notice/
# https://github.com/foundObjects/pve-nag-buster
- name: Ensure line in file to remove nag message modified.
  ansible.builtin.replace:
    path: /usr/share/javascript/proxmox-widget-toolkit/proxmoxlib.js
    regexp: 'res[\s\n]*\.data\.status\.toLowerCase\(\) !== .active.'
    replace: "false"
    backup: true
  notify: Restart pveproxy
