---

- name: Ensure GRUB_CMDLINE_LINUX_DEFAULT configed.
  ansible.builtin.lineinfile:
    path: /etc/default/grub
    regexp: '^GRUB_CMDLINE_LINUX_DEFAULT='
    line: GRUB_CMDLINE_LINUX_DEFAULT="quiet {{ cpu }}_iommu=on iommu=pt"
    state: present
  notify:
    - Update grub
    - Reboot
