---

- name: Update grub
  ansible.builtin.command: update-grub
  changed_when: true

# - name: Update initramfs
#   ansible.builtin.command: update-initramfs -u -k all
#   changed_when: true

- name: Reboot
  ansible.builtin.reboot:
