---

- name: Ensure mountpoints exists.
  ansible.builtin.file:
    path: "{{ item.path }}"
    state: "{{ 'absent' if item.state | default('mounted') == 'absent' else 'directory' }}"
    owner: nobody
    group: nogroup
    mode: "0775"
  with_items:
    - "{{ extra_mountpoints | default([]) }}"
    - "{{ disks | default([]) }}"
    - "{{ parity_disks | default([]) }}"

- name: Ensure points mounted.
  ansible.posix.mount:
    src: "{{ item.src }}"
    path: "{{ item.path }}"
    fstype: "{{ item.fs }}"
    opts: "{{ item.opts }}"
    state: "{{ item.state | default('mounted') }}"
  when: item.src is defined and item.fs is defined
  with_items:
    - "{{ extra_mountpoints | default([]) }}"
    - "{{ disks | default([]) }}"
    - "{{ parity_disks | default([]) }}"
