---

- name: Ensure mountpoints exists.
  ansible.builtin.file:
    dest: "{{ item.path }}"
    state: directory
    owner: nobody
    group: nogroup
    mode: "0775"
  with_items:
    - "{{ extra_mountpoints }}"
    - "{{ disks }}"
    - "{{ parity_disks }}"

- name: Ensure disks mounted.
  ansible.posix.mount:
    name: "{{ item.path }}"
    src: "{{ item.diskbyuuid }}"
    fstype: "{{ item.fs }}"
    opts: "{{ item.opts }}"
    state: "{{ item.state | default('mounted') }}"
  with_items:
    - "{{ extra_mountpoints }}"
    - "{{ disks }}"
    - "{{ parity_disks }}"
  when: item.diskbyuuid is defined and item.fs is defined

- name: Ensure mergerfs mounted.
  ansible.posix.mount:
    name: "{{ item.mountpoint }}"
    src: "{{ item.source }}"
    opts: "{{ item.opts }}"
    fstype: "{{ item.fs }}"
    state: mounted
  with_items:
    - "{{ fstab_mergerfs }}"
