---

- name: Ensure docker deamon.json exists.
  template:
    src: templates/deamon.json.j2
    dest: /etc/docker/daemon.json
    owner: root
    group: root
    mode: '0644'
  notify:
    - Reload daemon
    - Restart docker
