---

- name: Enuse CT Templates source replaced.
  ansible.builtin.replace:
    path: /usr/share/perl5/PVE/APLInfo.pm
    regexp: http://download.proxmox.com
    replace: "{{ ct_mirror }}"
    backup: true
  notify:
    - Restart pvedaemon
