version: '3'

services:
  smokeping:
    image: lscr.r00m.online/linuxserver/smokeping
    container_name: smokeping
    environment:
      - TZ=Asia/Shanghai
    volumes:
      - /path/to/smokeping/config:/config
      - /path/to/smokeping/data:/data
    restart: unless-stopped
